apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: observability
    toolkit.fluxcd.io/tenant: observability
    pod-security.kubernetes.io/enforce: privileged

