apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring # Adjust namespace as needed
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      #version: "0.69.0"  # Specify your desired version or omit for latest
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus
        namespace: flux-system
