apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: proxmox-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "0.3.5"
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi
        namespace: proxmox-csi
  values:
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 100Mi
    node:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 100m
          memory: 100Mi
    storageClass:
      - name: proxmox-data-ext4
        storage: vm_pool
        reclaimPolicy: Delete
        fstype: ext4
