apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: proxmox-csi
  namespace: proxmox-csi
spec:
  interval: 1h
  url: https://sergelogvinov.github.io/proxmox-csi-plugin
