# infra-controllers/storage/proxmox-csi/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: proxmox-csi
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:Jhp23pdNKpJGyoBy5mH+2uKJet+0q3eQu9Z+1lPND3719PhN8yi5Vz+G3dCCtPHJiUBr8rTupvx9aIEed+hri5IVgpee3Iq2GAdQtqiQfaK9tFokmvDlZlMSSTdAEYhFw6prQz7is6whuh60bNkAe+/pt1jumXO6Eeqbv/livYDJxjsAAD6F/hP9Lpo5xUDCbjhJYeVyvLrdMJcD0tDPtDeQqbvnECJHWIC/c7iIJApL4s/wLhzkbb4+3bX4FzwkZYheoz+PL1ddEg==,iv:Mgr1RKGsdGOFXUSaWOkU+M/nfULveohVinpRV0Clvhc=,tag:DM683j2ZkKCKIxGtP/iYlQ==,type:str]
sops:
    age:
        - recipient: age1jcyuy0zd86kz9c3wa5ft5q25lvgwwz7vql6jr88pq4e4h3upcuxq7mhy73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWnFXTklkaXR2c1loZlBF
            NGpFVlNoaHNkQnhZUHNMbVVPSmtEd0FzcFFZCkRBMFpudEh6RldtbnJxeEZ6NzNm
            UCszYXpXT0NCU0k1Y0xkVlg4QmFWQkEKLS0tIGhBOS8zYXlVS29lVWFDT1BVY1l3
            clkwMGpML291UlJXRHpoWEVwenZwVlEKeaG6U6bwF2eeqEkTaKLRCxtjYByB1g1I
            IQJxtBPftZqxvAlqltDFa/VgfnKWOBQFQM95MQ0PPKL0X0hKIhtikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T21:15:12Z"
    mac: ENC[AES256_GCM,data:h7pI+tBaStPjDVuAyq3sFOaOnBc5WDRZM/kBWHsDzy1I+tEGTLRdV19GkQ6KZxTZMrdI5qdf4aPfKPQGm7T1jqfiTh1FZ1KPx8ugSZFjAFqKVoBVvVC/oIWYNuh7qn8hSg/iAz4LFb8VbkMTL0aHcSXJAvQtrNSXnGMrlnHgjeU=,iv:TbIcD1DbkqFZ6rXlxX8LZY8Aupgjpv7JzKECXszJ2tU=,tag:qozspxeagM5VV1gzHuryrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
