apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lgtm-distributed
  namespace: monitoring # Adjust namespace as needed
spec:
  interval: 5m
  chart:
    spec:
      chart: lgtm-distributed
      #version: "0.69.0"  # Specify your desired version or omit for latest
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      grafana.ini:
        auth.generic_oauth:
          enabled: true
          name: "OIDC"
          scopes: "openid profile email"
          auth_url: "https://idp.emperor-anaconda.ts.net/oauth2/auth"
          token_url: "https://idp.emperor-anaconda.ts.net/oauth2/token"
          api_url: "https://idp.emperor-anaconda.ts.net/"
          allow_sign_up: true
          role_attribute_path: "contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'"
          email_attribute_path: "email"
          name_attribute_path: "name"
          login_attribute_path: "email"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    distributor:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    nginx:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    queryFrontend:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    compactor:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    querier:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    ingester:
      securityContext:
        seccompProfile:
          type: RuntimeDefault